import { useMutation, useQuery } from '@tanstack/react-query'
import { AlertTriangle, CheckCircle2, Copy, FileText, GitBranch, Lightbulb, Network, Sparkles } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { getAnalysis, startAnalysis, startGeneration } from '../api/client'
import { PageSkeleton } from '../components/LoadingSkeleton'

export function AnalysisPage() {
  const { analysisId = '' } = useParams()
  const navigate = useNavigate()
  const query = useQuery({ queryKey: ['analysis', analysisId], queryFn: () => getAnalysis(analysisId), enabled: Boolean(analysisId) })
  const generation = useMutation({ mutationFn: () => startGeneration(analysisId), onSuccess: result => navigate(`/generations/${result.generationId}`) })
  const retryAnalysis = useMutation({ mutationFn: async () => { const current = query.data; if (!current) throw new Error('The analysis is not available to retry.'); return startAnalysis(current.uploadId, true) }, onSuccess: result => navigate(`/analyses/${result.analysisId}`) })

  if (query.isLoading) return <PageSkeleton cards={6} rows={2} />
  if (query.isError) return <div className="rounded-xl bg-rose-50 p-5 text-rose-700">{query.error.message}</div>
  const analysis = query.data!
  if (analysis.status === 'Failed') return <section className="mx-auto max-w-2xl"><Link to={`/uploads/${analysis.uploadId}`} className="text-sm font-semibold text-teal-700">← Back to archive</Link><div className="mt-8 rounded-xl border border-rose-200 bg-rose-50 p-6"><h1 className="text-2xl font-semibold text-rose-900">Knowledge analysis could not be completed</h1><p className="mt-2 text-rose-800">{analysis.errorMessage ?? 'No additional AI request was made automatically. You can retry manually.'}</p><button type="button" disabled={retryAnalysis.isPending} onClick={() => retryAnalysis.mutate()} className="mt-5 rounded-lg bg-rose-800 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{retryAnalysis.isPending ? 'Retrying analysis…' : 'Retry analysis'}</button></div></section>
  const d = analysis.discovery
  if (!d) return <PageSkeleton cards={6} rows={2} />
  const metrics = [
    ['Documents analyzed', analysis.documentsAnalyzed, FileText, 'text-sky-700 bg-sky-50'],
    ['Knowledge domains', d.domains.length, Network, 'text-teal-700 bg-teal-50'],
    ['Topics discovered', d.topics.length, Lightbulb, 'text-violet-700 bg-violet-50'],
    ['Duplicate groups', d.duplicateGroups.length, Copy, 'text-amber-700 bg-amber-50'],
    ['Conflicts detected', d.conflicts.length, AlertTriangle, 'text-rose-700 bg-rose-50'],
    ['Articles proposed', d.suggestedArticles.length, Sparkles, 'text-teal-700 bg-teal-50'],
  ] as const

  return <section className="animate-fade-in">
    <Link to={`/uploads/${analysis.uploadId}`} className="text-sm font-semibold text-teal-700 hover:text-teal-900">← Back to archive</Link>
    <div className="mt-6 rounded-2xl border border-teal-200 bg-gradient-to-br from-teal-50 via-white to-sky-50 p-6 sm:p-8"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-teal-700">Knowledge map</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">Your knowledge has been understood</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-slate-600">OrgWiki analyzed the complete document corpus, mapped the organization&apos;s knowledge structure, and identified the areas that need human attention.</p><p className="mt-5 flex items-center gap-2 text-sm font-medium text-teal-800"><CheckCircle2 size={17} />Validated discovery is ready for controlled article generation.</p></div>
    <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{metrics.map(([label, value, Icon, colour]) => <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm transition duration-200 hover:-translate-y-0.5 hover:shadow-md" key={label}><div className="flex items-start justify-between"><span className={`grid size-9 place-items-center rounded-lg ${colour}`}><Icon size={18} /></span><p className="text-3xl font-semibold tracking-tight text-slate-950">{value}</p></div><p className="mt-4 text-sm font-medium text-slate-600">{label}</p></div>)}</div>
    <div className="mt-10 grid gap-6 lg:grid-cols-2"><div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-semibold"><Network size={19} className="text-teal-700" />Knowledge domains</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{d.domains.map(domain => <div key={domain.key} className="rounded-lg border border-slate-100 bg-slate-50 p-4"><p className="font-semibold text-slate-900">{domain.name}</p><p className="mt-2 text-sm leading-6 text-slate-600">{domain.description}</p><p className="mt-3 text-xs font-semibold text-teal-700">{d.topics.filter(t => t.domainKey === domain.key).length} topics</p></div>)}</div></div><div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-semibold"><Sparkles size={19} className="text-teal-700" />Suggested knowledge structure</h2><div className="mt-5 space-y-3">{d.suggestedArticles.map(article => <div key={article.key} className="rounded-lg border border-slate-100 p-4"><p className="font-semibold">{article.title}</p><p className="mt-1 text-sm leading-6 text-slate-600">{article.summary}</p></div>)}</div></div></div>
    {d.conflicts.length > 0 && <div className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-6"><h2 className="flex items-center gap-2 text-lg font-semibold text-amber-950"><AlertTriangle size={19} />Documentation conflicts needing review</h2><p className="mt-2 text-sm text-amber-900">These claims cannot both be true in the same context. They remain unresolved for human review.</p><div className="mt-5 space-y-4">{d.conflicts.map((conflict, index) => <div key={index} className="rounded-lg border border-amber-200 bg-white p-4"><p className="font-semibold">{conflict.title}</p><div className="mt-3 grid gap-3 md:grid-cols-2"><blockquote className="border-l-2 border-amber-400 pl-3 text-sm leading-6">{conflict.evidenceSnippetA}</blockquote><blockquote className="border-l-2 border-amber-400 pl-3 text-sm leading-6">{conflict.evidenceSnippetB}</blockquote></div><p className="mt-3 text-sm text-amber-900"><strong>Recommendation:</strong> {conflict.recommendation}</p></div>)}</div></div>}
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-semibold"><GitBranch size={19} className="text-teal-700" />Topic relationships</h2><div className="mt-4 space-y-3 text-sm">{d.relationships.length ? d.relationships.map((relationship, index) => <p key={index} className="rounded-lg bg-slate-50 px-3 py-2"><strong>{relationship.sourceTopicKey}</strong><span className="mx-2 font-medium text-teal-700">{relationship.type}</span><strong>{relationship.targetTopicKey}</strong></p>) : <p className="text-slate-500">No topic relationships were identified in this corpus.</p>}</div></div><div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">Knowledge health</h2><div className="mt-4 space-y-4 text-sm">{d.duplicateGroups.length ? <div><p className="font-semibold">Duplicate knowledge</p>{d.duplicateGroups.map((group, index) => <p key={index} className="mt-1 leading-6 text-slate-600"><strong>{group.title}</strong> — {group.explanation}</p>)}</div> : <p className="text-slate-500">No meaningful duplicate knowledge groups were found.</p>}{d.outdatedCandidates.length ? <div><p className="font-semibold">Potentially outdated knowledge</p>{d.outdatedCandidates.map((item, index) => <p key={index} className="mt-1 leading-6 text-slate-600"><strong>{item.description}</strong> — {item.reason}</p>)}</div> : <p className="text-slate-500">No potentially outdated knowledge was identified.</p>}</div></div></div>
    <div className="mt-8 flex flex-wrap items-center justify-between gap-4 rounded-xl border border-teal-200 bg-teal-50 p-5"><div><p className="font-semibold text-teal-900">Turn this map into reviewed knowledge</p><p className="mt-1 text-sm text-teal-800">Generate all proposed articles in one controlled AI request.</p></div><button type="button" disabled={generation.isPending} onClick={() => generation.mutate()} className="rounded-lg bg-teal-700 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-teal-800 disabled:opacity-50">{generation.isPending ? 'Generating articles…' : 'Generate articles'}</button></div>
    {generation.isError && <p className="mt-3 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{generation.error.message}</p>}
  </section>
}
