import { useQuery } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import { CheckCircle2, LoaderCircle } from 'lucide-react'
import { getGeneration } from '../api/client'

export function GeneratedArticlesPage() {
  const { generationId = '' } = useParams()
  const query = useQuery({ queryKey: ['generation', generationId], queryFn: () => getGeneration(generationId), enabled: Boolean(generationId) })
  if (query.isLoading) return <div className="flex items-center gap-3 text-slate-600"><LoaderCircle className="animate-spin" size={20} />Generating your knowledge articles…</div>
  if (query.isError) return <div className="rounded-xl bg-rose-50 p-5 text-rose-700">{query.error.message}</div>
  const generation = query.data!
  if (generation.status === 'Failed') return <section><Link to={`/analyses/${generation.analysisId}`} className="text-sm font-semibold text-teal-700">← Back to analysis</Link><div className="mt-8 rounded-xl bg-rose-50 p-6"><h1 className="text-2xl font-semibold text-rose-900">Article generation could not be completed</h1><p className="mt-2 text-rose-800">{generation.errorMessage ?? 'No additional AI request was made automatically. You can retry manually.'}</p></div></section>
  if (!generation.result) return <div className="flex items-center gap-3 text-slate-600"><LoaderCircle className="animate-spin" size={20} />Preparing generated articles…</div>
  return <section><Link to={`/analyses/${generation.analysisId}`} className="text-sm font-semibold text-teal-700">← Back to analysis</Link><div className="mt-6"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-teal-700">Knowledge generation</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">Generated articles</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-slate-600">These validated Markdown articles are ready for human review.</p></div><div className="mt-8 space-y-6">{generation.result.articles.map(article => <article key={article.key} className="rounded-xl border border-slate-200 bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-semibold">{article.title}</h2><p className="mt-2 text-slate-600">{article.summary}</p></div><span className="rounded-full bg-amber-100 px-3 py-1 text-sm font-semibold text-amber-800">Pending review</span></div><div className="mt-5 flex flex-wrap gap-2 text-xs text-slate-500"><span>{article.difficulty}</span><span>•</span><span>{article.estimatedReadingMinutes} min read</span><span>•</span><span>{article.citations.length} citations</span></div><pre className="mt-5 overflow-x-auto whitespace-pre-wrap rounded-lg bg-slate-950 p-5 text-sm leading-6 text-slate-100">{article.markdownContent}</pre><div className="mt-5 space-y-2">{article.citations.map((citation, index) => <div key={index} className="rounded-lg border border-slate-200 bg-slate-50 p-3 text-sm"><p className="font-medium text-slate-700">Source {citation.sourceDocumentId}</p><p className="mt-1 text-slate-600">“{citation.evidenceSnippet}”</p></div>)}</div></article>)}</div><p className="mt-8 flex items-center gap-2 text-sm text-slate-500"><CheckCircle2 size={16} className="text-teal-700" />Publishing and editing belong to later phases.</p></section>
}
