import { useQuery } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import { CheckCircle2, Clock3, FileCheck2, Sparkles, Tag } from 'lucide-react'
import { getGeneration } from '../api/client'
import { PageSkeleton } from '../components/LoadingSkeleton'
import { SafeMarkdown } from '../components/SafeMarkdown'

export function GeneratedArticlesPage() {
  const { generationId = '' } = useParams()
  const query = useQuery({ queryKey: ['generation', generationId], queryFn: () => getGeneration(generationId), enabled: Boolean(generationId) })
  if (query.isLoading) return <PageSkeleton cards={3} rows={2} />
  if (query.isError) return <div className="rounded-xl bg-rose-50 p-5 text-rose-700">{query.error.message}</div>
  const generation = query.data!
  if (generation.status === 'Failed') return <section><Link to={`/analyses/${generation.analysisId}`} className="text-sm font-semibold text-teal-700">← Back to analysis</Link><div className="mt-8 rounded-xl border border-rose-200 bg-rose-50 p-6"><h1 className="text-2xl font-semibold text-rose-900">Article generation could not be completed</h1><p className="mt-2 text-rose-800">{generation.errorMessage ?? 'No additional AI request was made automatically. You can retry manually.'}</p></div></section>
  if (!generation.result) return <PageSkeleton cards={3} rows={2} />
  return <section className="animate-fade-in"><Link to={`/analyses/${generation.analysisId}`} className="text-sm font-semibold text-teal-700 hover:text-teal-900">← Back to analysis</Link><div className="mt-6 rounded-2xl border border-teal-200 bg-gradient-to-br from-teal-50 via-white to-sky-50 p-6 sm:p-8"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-teal-700">Knowledge generation</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">Your knowledge articles are ready</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-slate-600">Each draft is grounded in validated source evidence and ready for human review.</p><p className="mt-5 flex items-center gap-2 text-sm font-medium text-teal-800"><Sparkles size={17} />{generation.result.articles.length} article{generation.result.articles.length === 1 ? '' : 's'} generated in one controlled request.</p></div><div className="mt-8 space-y-6">{generation.result.articles.map(article => <article key={article.key} className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold text-teal-700">Generated knowledge article</p><h2 className="mt-2 text-2xl font-semibold tracking-tight">{article.title}</h2><p className="mt-2 max-w-3xl leading-7 text-slate-600">{article.summary}</p></div><span className="rounded-full bg-amber-100 px-3 py-1.5 text-sm font-semibold text-amber-800">Pending review</span></div><div className="mt-5 flex flex-wrap items-center gap-x-4 gap-y-2 border-y border-slate-100 py-3 text-sm text-slate-500"><span className="inline-flex items-center gap-1.5"><Clock3 size={15} />{article.estimatedReadingMinutes} min read</span><span>{article.difficulty}</span><span className="inline-flex items-center gap-1.5"><FileCheck2 size={15} />{article.citations.length} verified citations</span><span>{Math.round(article.confidence * 100)}% confidence</span></div><div className="mt-6"><SafeMarkdown content={article.markdownContent} /></div><div className="mt-6 flex flex-wrap gap-2">{article.tags.map(tag => <span key={tag} className="inline-flex items-center gap-1 rounded-md bg-slate-100 px-2 py-1 text-xs font-medium text-slate-600"><Tag size={12} />{tag}</span>)}</div></article>)}</div><p className="mt-8 flex items-center gap-2 text-sm text-slate-500"><CheckCircle2 size={16} className="text-teal-700" />Continue to review to validate, approve, and publish this knowledge.</p></section>
}
