import { useQuery } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import { LoaderCircle } from 'lucide-react'
import { getKnowledgeArticle } from '../api/client'
import { SafeMarkdown } from '../components/SafeMarkdown'

export function KnowledgeArticlePage() {
  const { articleKey = '' } = useParams(); const query = useQuery({ queryKey: ['knowledge-article', articleKey], queryFn: () => getKnowledgeArticle(articleKey), enabled: Boolean(articleKey) })
  if (query.isLoading) return <div className="flex items-center gap-3 text-slate-600"><LoaderCircle className="animate-spin" size={20} />Loading published knowledge…</div>
  if (query.isError) return <div className="rounded-xl bg-rose-50 p-5 text-rose-700">This published article could not be found.</div>
  const article = query.data!; return <article><Link to="/knowledge" className="text-sm font-semibold text-teal-700">← Knowledge Base</Link><p className="mt-7 text-sm font-semibold uppercase tracking-[0.18em] text-teal-700">{article.domain}</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">{article.title}</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-slate-600">{article.summary}</p><div className="mt-5 flex flex-wrap gap-3 text-sm text-slate-500"><span>{article.difficulty}</span><span>•</span><span>{article.estimatedReadingMinutes} min read</span><span>•</span><span>Published {new Date(article.publishedAtUtc).toLocaleDateString()}</span>{article.tags.map(tag => <span key={tag} className="rounded bg-teal-50 px-2 py-1 text-teal-800">{tag}</span>)}</div><div className="mt-10 max-w-3xl"><SafeMarkdown content={article.markdownContent} /></div><section className="mt-12"><h2 className="text-2xl font-semibold">Related articles</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{article.relatedArticles.map(item => <Link key={item.key} to={`/knowledge/articles/${item.key}`} className="rounded-xl border border-slate-200 bg-white p-4"><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm text-slate-600">{item.summary}</p></Link>)}</div>{article.relatedArticles.length === 0 && <p className="mt-3 text-sm text-slate-500">No related articles are currently published.</p>}</section><section className="mt-12 rounded-xl border border-teal-200 bg-teal-50 p-6"><h2 className="text-2xl font-semibold text-teal-950">Source Evidence</h2><p className="mt-2 text-sm text-teal-900">Exact supporting snippets from the reviewed source material.</p><div className="mt-5 space-y-4">{article.citations.map((citation, index) => <div key={index} className="rounded-lg border border-teal-100 bg-white p-4"><p className="font-semibold text-slate-900">{citation.sourceFileName}</p><p className="text-xs text-slate-500">{citation.sourcePath}</p><blockquote className="mt-3 max-h-48 overflow-auto whitespace-pre-wrap border-l-4 border-teal-500 pl-4 text-slate-700">{citation.evidenceSnippet}</blockquote></div>)}</div></section></article>
}
