import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { useState } from 'react'
import { LoaderCircle, Search } from 'lucide-react'
import { getKnowledgeBase, searchKnowledge } from '../api/client'

export function KnowledgeBasePage() {
  const [input, setInput] = useState(''); const [query, setQuery] = useState(''); const [domain, setDomain] = useState(''); const [tag, setTag] = useState('')
  const home = useQuery({ queryKey: ['knowledge-home'], queryFn: getKnowledgeBase })
  const results = useQuery({ queryKey: ['knowledge-search', query], queryFn: () => searchKnowledge(query), enabled: Boolean(query) })
  if (home.isLoading) return <div className="flex items-center gap-3 text-slate-600"><LoaderCircle className="animate-spin" size={20} />Loading Knowledge Base…</div>
  if (home.isError) return <div className="rounded-xl bg-rose-50 p-5 text-rose-700">{home.error.message}</div>
  const data = home.data!; const base = query ? (results.data ?? []) : data.articles; const articles = base.filter(article => (!domain || article.domain === domain) && (!tag || article.tags.includes(tag)))
  return <section><div className="rounded-2xl bg-slate-950 px-6 py-10 text-white sm:px-10"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-teal-300">OrgWiki Knowledge Base</p><h1 className="mt-3 text-4xl font-semibold">Trusted organizational knowledge</h1><p className="mt-4 max-w-2xl text-slate-300">Consolidated from reviewed source material with verifiable evidence.</p><form className="mt-7 flex max-w-2xl gap-2" onSubmit={event => { event.preventDefault(); setQuery(input.trim()) }}><input value={input} onChange={event => setInput(event.target.value)} placeholder="Search published knowledge" className="min-w-0 flex-1 rounded-lg px-4 py-3 text-slate-950" /><button className="inline-flex items-center gap-2 rounded-lg bg-teal-500 px-4 py-3 font-semibold text-slate-950"><Search size={17} />Search</button>{query && <button type="button" onClick={() => { setInput(''); setQuery('') }} className="rounded-lg border border-slate-600 px-4 py-3">Clear</button>}</form></div><div className="mt-8 flex flex-wrap gap-3 text-sm"><span className="rounded-full bg-teal-100 px-3 py-1.5 font-semibold text-teal-800">{data.publishedArticleCount} published articles</span>{data.domains.map(value => <button key={value} onClick={() => setDomain(domain === value ? '' : value)} className={`rounded-full px-3 py-1.5 ${domain === value ? 'bg-slate-900 text-white' : 'bg-slate-100 text-slate-700'}`}>{value}</button>)}{data.tags.map(value => <button key={value} onClick={() => setTag(tag === value ? '' : value)} className={`rounded-full px-3 py-1.5 ${tag === value ? 'bg-teal-700 text-white' : 'bg-teal-50 text-teal-800'}`}>#{value}</button>)}</div>{query && <p className="mt-6 text-sm text-slate-600">Search results for “{query}” — {articles.length} found</p>}{results.isError && <p className="mt-5 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{results.error.message}</p>}<div className="mt-6 grid gap-4 md:grid-cols-2">{articles.map(article => <Link key={article.key} to={`/knowledge/articles/${article.key}`} className="rounded-xl border border-slate-200 bg-white p-5 transition hover:border-teal-400"><p className="text-sm font-semibold text-teal-700">{article.domain}</p><h2 className="mt-2 text-xl font-semibold">{article.title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{article.summary}</p><div className="mt-4 flex flex-wrap gap-2 text-xs text-slate-500"><span>{article.difficulty}</span><span>•</span><span>{article.estimatedReadingMinutes} min read</span>{article.tags.map(value => <span key={value} className="rounded bg-slate-100 px-2 py-1">{value}</span>)}</div></Link>)}</div>{articles.length === 0 && <div className="mt-8 rounded-xl border border-dashed border-slate-300 bg-white p-8 text-center text-slate-600">No published knowledge matches this view. Approved articles must be explicitly published before they appear here.</div>}</section>
}
