import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { BookOpenCheck, CalendarDays, Clock3, FolderOpen, Search, Tags } from 'lucide-react'
import { useState } from 'react'
import { getKnowledgeBase } from '../api/client'
import { PageSkeleton } from '../components/LoadingSkeleton'

export function KnowledgeBasePage() {
  const [filter, setFilter] = useState('')
  const [domain, setDomain] = useState('')
  const [tag, setTag] = useState('')
  const home = useQuery({ queryKey: ['knowledge-home'], queryFn: getKnowledgeBase })
  if (home.isLoading) return <PageSkeleton cards={4} rows={2} />
  if (home.isError) return <div className="rounded-xl bg-rose-50 p-5 text-rose-700">{home.error.message}</div>
  const data = home.data!
  const term = filter.trim().toLowerCase()
  const articles = data.articles.filter(article => (!term || `${article.title} ${article.summary} ${article.domain} ${article.tags.join(' ')}`.toLowerCase().includes(term)) && (!domain || article.domain === domain) && (!tag || article.tags.includes(tag)))

  return <section className="animate-fade-in"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-teal-700">Knowledge Base</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-4xl font-semibold tracking-tight">Trusted organizational knowledge</h1><p className="mt-3 max-w-2xl text-slate-600">Reviewed knowledge, published with immutable evidence from your organization&apos;s source material.</p></div><div className="rounded-xl bg-teal-50 px-4 py-3 text-right"><p className="text-2xl font-semibold text-teal-900">{data.publishedArticleCount}</p><p className="text-xs font-semibold uppercase tracking-wide text-teal-700">Published articles</p></div></div></div>
    <div className="mt-6 rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18} /><input value={filter} onChange={event => setFilter(event.target.value)} placeholder="Filter by title, summary, tag, or domain" className="w-full rounded-lg border border-slate-300 py-2.5 pl-10 pr-3 text-sm outline-none transition focus:border-teal-600 focus:ring-2 focus:ring-teal-100" /></div><div className="mt-4 flex flex-wrap gap-2"><span className="mr-1 inline-flex items-center gap-1.5 px-1 py-2 text-xs font-semibold uppercase tracking-wide text-slate-500"><FolderOpen size={14} />Domains</span>{data.domains.map(value => <button key={value} onClick={() => setDomain(domain === value ? '' : value)} className={`rounded-lg px-3 py-2 text-sm font-medium transition ${domain === value ? 'bg-slate-900 text-white shadow-sm' : 'bg-slate-50 text-slate-700 hover:bg-slate-100'}`}>{value}</button>)}</div><div className="mt-2 flex flex-wrap gap-2"><span className="mr-1 inline-flex items-center gap-1.5 px-1 py-2 text-xs font-semibold uppercase tracking-wide text-slate-500"><Tags size={14} />Tags</span>{data.tags.map(value => <button key={value} onClick={() => setTag(tag === value ? '' : value)} className={`rounded-lg px-3 py-2 text-sm font-medium transition ${tag === value ? 'bg-teal-700 text-white shadow-sm' : 'bg-teal-50 text-teal-800 hover:bg-teal-100'}`}>#{value}</button>)}</div></div>
    <div className="mt-7 flex items-center justify-between"><p className="text-sm text-slate-600">{filter || domain || tag ? `${articles.length} matching article${articles.length === 1 ? '' : 's'}` : `${articles.length} published article${articles.length === 1 ? '' : 's'}`}</p>{(filter || domain || tag) && <button type="button" onClick={() => { setFilter(''); setDomain(''); setTag('') }} className="text-sm font-semibold text-teal-700 hover:text-teal-900">Clear filters</button>}</div>
    <div className="mt-5 grid gap-5 md:grid-cols-2">{articles.map(article => <Link key={article.key} to={`/knowledge/articles/${article.key}`} className="group rounded-xl border border-slate-200 bg-white p-6 shadow-sm transition duration-200 hover:-translate-y-1 hover:border-teal-300 hover:shadow-md"><div className="flex items-start justify-between gap-4"><span className="rounded-full bg-teal-50 px-2.5 py-1 text-xs font-semibold text-teal-800">{article.domain}</span><BookOpenCheck size={20} className="text-slate-300 transition group-hover:text-teal-700" /></div><h2 className="mt-4 text-xl font-semibold tracking-tight text-slate-950">{article.title}</h2><p className="mt-2 leading-6 text-slate-600">{article.summary}</p><div className="mt-5 flex flex-wrap items-center gap-x-4 gap-y-2 border-t border-slate-100 pt-4 text-xs font-medium text-slate-500"><span className="inline-flex items-center gap-1.5"><Clock3 size={14} />{article.estimatedReadingMinutes} min read</span><span className="inline-flex items-center gap-1.5"><CalendarDays size={14} />{new Date(article.publishedAtUtc).toLocaleDateString()}</span><span>{article.relatedArticleCount} related</span></div><div className="mt-4 flex flex-wrap gap-2">{article.tags.map(value => <span key={value} className="rounded-md bg-slate-100 px-2 py-1 text-xs font-medium text-slate-600">{value}</span>)}</div><p className="mt-5 text-sm font-semibold text-teal-700">View article →</p></Link>)}</div>
    {articles.length === 0 && <div className="mt-8 rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center"><BookOpenCheck className="mx-auto text-slate-400" size={28} /><h2 className="mt-4 font-semibold text-slate-900">No published knowledge matches this view</h2><p className="mt-2 text-sm text-slate-600">As your knowledge base grows, OrgWiki will help you find and navigate reviewed organizational knowledge.</p></div>}</section>
}
