import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { CheckCircle2, FileCheck2, Send, XCircle } from 'lucide-react'
import { getReviewDashboard } from '../api/client'
import { useState } from 'react'
import { PageSkeleton } from '../components/LoadingSkeleton'

const statuses = ['All', 'PendingReview', 'Approved', 'Rejected', 'Published']
const statusStyle: Record<string, string> = { PendingReview: 'bg-amber-100 text-amber-800', Approved: 'bg-sky-100 text-sky-800', Rejected: 'bg-rose-100 text-rose-800', Published: 'bg-emerald-100 text-emerald-800' }
const statusIcon: Record<string, typeof FileCheck2> = { PendingReview: FileCheck2, Approved: CheckCircle2, Rejected: XCircle, Published: Send }

export function ReviewDashboardPage() {
  const query = useQuery({ queryKey: ['review-dashboard'], queryFn: getReviewDashboard })
  const [status, setStatus] = useState('All')
  const [search, setSearch] = useState('')
  const articles = (query.data?.articles ?? []).filter(article => (status === 'All' || article.status === status) && `${article.title} ${article.tags.join(' ')} ${article.domain}`.toLowerCase().includes(search.toLowerCase()))
  if (query.isLoading) return <PageSkeleton cards={4} rows={3} />
  if (query.isError) return <div className="rounded-xl bg-rose-50 p-5 text-rose-700">{query.error.message}</div>
  const dashboard = query.data!
  const metrics = [['Pending review', dashboard.pendingReview, 'bg-amber-50 text-amber-800'], ['Approved', dashboard.approved, 'bg-sky-50 text-sky-800'], ['Rejected', dashboard.rejected, 'bg-rose-50 text-rose-800'], ['Published', dashboard.published, 'bg-emerald-50 text-emerald-800']]
  return <section className="animate-fade-in"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-teal-700">Review</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">Knowledge review queue</h1><p className="mt-3 text-slate-600">Human approval turns AI-generated drafts into trusted organizational knowledge.</p></div><div className="mt-8 grid gap-3 sm:grid-cols-4">{metrics.map(([label, value, colour]) => <div key={label as string} className={`rounded-xl border border-slate-200 p-5 shadow-sm ${colour}`}><p className="text-sm font-medium">{label}</p><p className="mt-1 text-3xl font-semibold tracking-tight">{value}</p></div>)}</div><div className="mt-8 rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Filter by title, tag, or domain" className="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-teal-600 focus:ring-2 focus:ring-teal-100" /><div className="mt-3 flex flex-wrap gap-2">{statuses.map(value => <button key={value} onClick={() => setStatus(value)} className={`rounded-lg px-3 py-2 text-sm font-medium transition ${status === value ? 'bg-teal-700 text-white shadow-sm' : 'bg-slate-50 text-slate-700 hover:bg-slate-100'}`}>{value === 'PendingReview' ? 'Pending review' : value}</button>)}</div></div><div className="mt-6 grid gap-4">{articles.map(article => { const Icon = statusIcon[article.status] ?? FileCheck2; return <Link to={`/review/articles/${article.id}`} key={article.id} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm transition duration-200 hover:-translate-y-0.5 hover:border-teal-300 hover:shadow-md"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold text-teal-700">{article.domain}</p><h2 className="mt-1 text-lg font-semibold">{article.title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{article.summary}</p></div><span className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1 text-xs font-semibold ${statusStyle[article.status] ?? 'bg-slate-100 text-slate-700'}`}><Icon size={13} />{article.status === 'PendingReview' ? 'Pending review' : article.status}</span></div><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 border-t border-slate-100 pt-4 text-sm text-slate-500"><span>{Math.round(article.confidence * 100)}% confidence</span><span>{article.citationCount} citations</span><span>{article.estimatedReadingMinutes} min read</span><span>{article.tags.length} tags</span></div></Link>})}</div>{articles.length === 0 && <div className="mt-6 rounded-xl border border-dashed border-slate-300 bg-white p-9 text-center text-sm leading-6 text-slate-600">No articles match this view. Generated knowledge will appear here when it is ready for human review.</div>}</section>
}
