import { useQuery } from '@tanstack/react-query'
import { CalendarDays, Clock3, Download, Link2, Tag } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { getPublicTeamSpaceArticle } from '../api/client'
import { PageSkeleton } from '../components/LoadingSkeleton'
import { PublicSpacesHeader } from '../components/PublicSpacesHeader'
import { SafeMarkdown } from '../components/SafeMarkdown'
import { downloadArticleMarkdown } from '../components/downloadMarkdown'

export function TeamSpaceArticlePage() {
  const { slug = '', articleSlug = '' } = useParams()
  const query = useQuery({ queryKey: ['public-team-space-article', slug, articleSlug], queryFn: () => getPublicTeamSpaceArticle(slug, articleSlug), enabled: Boolean(slug && articleSlug) })
  if (query.isLoading) return <div className="min-h-screen bg-stone-50"><PublicSpacesHeader /><main className="mx-auto max-w-5xl px-5 py-12 sm:px-8"><PageSkeleton cards={2} rows={3} /></main></div>
  if (query.isError) return <div className="min-h-screen bg-stone-50"><PublicSpacesHeader /><main className="mx-auto max-w-5xl px-5 py-12 text-rose-700">This published article could not be found in this Team Space.</main></div>
  const article = query.data!
  return <div className="min-h-screen bg-stone-50 text-slate-950"><PublicSpacesHeader /><main className="mx-auto max-w-5xl px-5 py-12 sm:px-8"><Link to={`/spaces/${slug}`} className="text-sm font-semibold text-teal-700 hover:text-teal-900">← Team Space</Link><article className="mt-6"><header className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-teal-700">Published knowledge</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">{article.title}</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-slate-600">{article.summary}</p></div><button type="button" onClick={() => downloadArticleMarkdown(article)} className="inline-flex cursor-pointer items-center gap-2 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-semibold text-slate-700 transition hover:bg-slate-50"><Download size={16} />Download Markdown</button></div><div className="mt-6 flex flex-wrap gap-x-5 gap-y-3 border-t border-slate-100 pt-5 text-sm text-slate-600"><span className="inline-flex items-center gap-2"><Clock3 size={16} className="text-teal-700" />{article.estimatedReadingMinutes} min read</span><span>{article.difficulty}</span><span className="inline-flex items-center gap-2"><CalendarDays size={16} className="text-teal-700" />Updated {new Date(article.lastUpdatedAtUtc).toLocaleDateString()}</span><span>Published {new Date(article.publishedAtUtc).toLocaleDateString()}</span></div><div className="mt-5 flex flex-wrap gap-2">{article.tags.map(tag => <span key={tag} className="inline-flex items-center gap-1 rounded-md bg-teal-50 px-2.5 py-1 text-xs font-semibold text-teal-800"><Tag size={12} />{tag}</span>)}</div></header><div className="mx-auto mt-10 max-w-3xl"><SafeMarkdown content={article.markdownContent} /></div><section className="mt-12"><div className="flex items-center gap-2"><Link2 size={20} className="text-teal-700" /><h2 className="text-2xl font-semibold">Related articles</h2></div><div className="mt-4 grid gap-4 md:grid-cols-2">{article.relatedArticles.map(item => <Link key={item.key} to={`/spaces/${slug}/${item.key}`} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-teal-300 hover:shadow-md"><p className="font-semibold">{item.title}</p><p className="mt-2 text-sm leading-6 text-slate-600">{item.summary}</p><p className="mt-4 text-sm font-semibold text-teal-700">Read article →</p></Link>)}</div>{article.relatedArticles.length === 0 && <p className="mt-4 rounded-lg border border-dashed border-slate-300 bg-white p-5 text-sm leading-6 text-slate-600">Related articles will appear here as more reviewed knowledge is shared in this Team Space.</p>}</section></article></main></div>
}
