import { useQuery } from '@tanstack/react-query'
import { ArrowRight, LibraryBig, UsersRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import { getPublicTeamSpaces } from '../api/client'
import { PageSkeleton } from '../components/LoadingSkeleton'
import { PublicSpacesHeader } from '../components/PublicSpacesHeader'

export function TeamSpacesPage() {
  const query = useQuery({ queryKey: ['public-team-spaces'], queryFn: getPublicTeamSpaces })
  return <div className="min-h-screen bg-stone-50 text-slate-950"><PublicSpacesHeader /><main className="mx-auto max-w-6xl px-5 py-12 sm:px-8"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-teal-700">Team Spaces</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">Published knowledge for every employee.</h1><p className="mt-4 text-lg leading-8 text-slate-600">Team Spaces are curated collections of reviewed organizational knowledge. They are public, read-only, and backed by the articles your knowledge team has chosen to share.</p></div>{query.isLoading ? <div className="mt-10"><PageSkeleton cards={3} rows={1} /></div> : query.isError ? <div className="mt-10 rounded-xl bg-rose-50 p-5 text-rose-700">Team Spaces could not be loaded.</div> : <div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{query.data!.map(space => <Link key={space.slug} to={`/spaces/${space.slug}`} className="group rounded-xl border border-slate-200 bg-white p-6 shadow-sm transition duration-200 hover:-translate-y-1 hover:border-teal-300 hover:shadow-md"><span className="grid size-11 place-items-center rounded-lg bg-teal-50 text-teal-700"><UsersRound size={21} /></span><h2 className="mt-5 text-xl font-semibold">{space.name}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-slate-600">{space.description}</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><span className="inline-flex items-center gap-2 text-sm font-medium text-slate-600"><LibraryBig size={16} />{space.articleCount} article{space.articleCount === 1 ? '' : 's'}</span><span className="inline-flex items-center gap-1 text-sm font-semibold text-teal-700">View Space <ArrowRight size={15} /></span></div></Link>)}</div>}{!query.isLoading && !query.isError && query.data?.length === 0 && <div className="mt-10 rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center"><UsersRound className="mx-auto text-slate-400" size={28} /><h2 className="mt-4 font-semibold">No Team Spaces have been published yet.</h2><p className="mt-2 text-sm text-slate-600">Once the knowledge team shares reviewed articles, they will appear here.</p></div>}</main></div>
}
